#!/usr/bin/env bash

filtered_root=$1

# loop through the array for each unique analysis subdirectory in the filtered_root directory
for analysis_id in "${filtered_root}"/*; do
    echo "Current analysis directory: ${analysis_id}"
    # get the path of the sample directory
    readarray -t sample_dir < <(find "${analysis_id}" -maxdepth 1 -mindepth 1 -type d -name "*sample*")

    # check if the sample directory is empty; if it is empty, skip
    if [ -z "${sample_dir[0]}" ]; then
        echo "Sample directory is non-existent in the ${analysis_id} directory. Skipping..."
        continue
    else
        # check elements in the array
        # print the first element
        echo "Sample directory count: " "${#sample_dir[@]}"
        # loop through the rest of the elements in the array
        for ((i=0; i<${#sample_dir[@]}; i++)); do
            echo "Sample directory $((i+1)): " "${sample_dir[i]}"
            # get the basename of the sample directory
            sample_dir_name=$(basename "${sample_dir[i]}")
            # get the sample ID from the basename
            sample_id=$(echo "${sample_dir_name}" | cut -d'_' -f2)
            echo "Analysis ID: ${analysis_id}" "Sample ID: ${sample_id}"
        done
    fi
done

echo "Extraction done!"