#!/usr/bin/env bash


############################################################################################################
# For TOBIAS, we need to merge individual peak files into a single peak file for each sample.

# The list of selected peak files per samples are:
# 1. bfilt.narrowPeak true rep
# 2. idr.conservative.narrowPeak true rep
# 3. idr.optimal.narrowPeak true rep
# 4. overlap.optimal.narrowPeak true rep
# 5. overlap.conservative.narrowPeak true rep

# let us gather the necessary files in one place first
# make sure that a copy of 'peak' folder for each sample of a dataset (use the flag --relative with rsync) has been transferred from the storage server to where this merging would be done.

# ensure that the structure in the peak_root folder below is as follows, with raw_peaks and merged_peaks as subfolders:
# peak_root
# ├── merged_peaks
# └── raw_peaks

# check if argument is provided
if [ $# -eq 0 ]; then
	echo "No arguments provided. Please provide the path to the croo_root folder and the path to the dataset list text file."	
	exit 1
fi

croo_root=$1
dataset_list=$2

# grab the basename of all the datasets based on the subfolders in the current directory
readarray -t datasets < "${dataset_list}"

# print the datasets
echo "${datasets[@]}"

# iterate through each dataset
for dataset in "${datasets[@]}"; do
	# get the path of the dataset in the croo_root
    dataset_path=$(find "${croo_root}" -maxdepth 1 -mindepth 1 -type d -name "${dataset}")
    # iterate through each sample
	for sample_dir in "${dataset_path}"/*; do
		# check if the file is a directory; if it is NOT a directory, skip
		if [ ! -d "${sample_dir}" ]; then
			continue
		else
			# get the sample name
			sample_name=$(basename "${sample_dir}")
			# capture the sample number
			if [[ $sample_name =~ (sample[0-9]{1,3}) ]]; then
  				substring="${BASH_REMATCH[1]}"
  				echo "Substring: $substring"
			fi
			# make a directory for the merged peaks
			mkdir -p /home/msazizan/cargospace/encd-atac-pl/expo/tobias_raw_inputs/input_peaks/"${dataset}"/sample-"${substring}"
			
            # initialize an array to store the peak files
			peak_files=()
			# find PEAK FILES for each dataset and transfer to the raw_peaks folder
			readarray -t peak_files < <(find "${dataset_path}" -type f \( -name "*_chrM_MT.pval0.01.300K.bfilt.narrowPeak.gz" -o -name "idr.*_peak.narrowPeak.gz" -o -name "overlap.*_peak.narrowPeak.gz" -o -name "*_chrM_MT.tn5.pval0.01.300K.bfilt.narrowPeak.gz" \))
			# check the peak file array for each sample
			echo "Peak files of $dataset sample $substring:" "${peak_files[@]}"
			# copy the peak files to raw_peaks folder
			for f in "${peak_files[@]}"; do
				rsync -avz "${f}" "/home/msazizan/cargospace/encd-atac-pl/expo/tobias_raw_inputs/input_peaks/${dataset}/sample-${substring}/"
			done

            # initialize an array to store the bigwig files
            bigwig_files=()
            # find BIGWIG FILES for each dataset and transfer to the raw_peaks folder
            readarray -t bigwig_files < <(find "${dataset_path}" -type f \( -name "*_chrM_MT.tn5.pval0.01.300K.bfilt.fc.signal.bigwig" -o -name "*_chrM_MT.tn5.pval0.01.300K.bfilt.fc.signal.bw" \))

		fi
	done
done

