#!/usr/bin/env bash
# shellcheck disable=SC1091

# load environment
eval "$(conda shell.bash hook)"
conda activate bashATAC

# check if argument is provided
if [ $# -ne 2 ]; then
	echo "No arguments provided. Please provide the path to the folder where individual dataset merged peak files are stored and the output folder path to be created."	
	exit 1
fi

input_merged_peaks_root=$1
output_final_merged=$2

# create output folder
mkdir -p "${output_final_merged}"

cat "${input_merged_peaks_root}"/* | sort -k1,1 -k2,2n | bedtools merge -c 4 -o distinct -i - > "${output_final_merged}/ALL_master_merged_peakset-v2.bed"

echo "Done."