#!/usr/bin/env bash
# This script is used to run the job on the NSCC cluster.

#PBS -N extract-tfbs-tobias-output
#PBS -l select=1:ncpus=4:mem=32GB
#PBS -l walltime=10:00:00
#PBS -j oe
#PBS -P personal
#PBS -q normal

bash /home/users/ntu/suffiazi/scripts/footprinting-workflow-scripts/scripts/rsync-filtered-tobias-output-to-odin.sh --live-run /home/users/ntu/suffiazi/scripts/footprinting-workflow-scripts/inputs/analysis-id-to-odin.txt