#!/usr/bin/env bash
# shellcheck disable=SC1091
# shellcheck disable=SC2153
# This script is used to run the job on the cluster.

#PBS -N 20230703_tobias_test
#PBS -P sbs_liyh

#PBS -q q256_free
#PBS -l select=1:ncpus=16:mpiprocs=16:mem=32gb
#PBS -l walltime=8:00:00

#PBS -m bea
#PBS -M suffi.azizan@ntu.edu.sg

#PBS -o /home/suffi.azizan/scratchspace/pipeline_scripts/tobias_snakemake_scripts/pbs_oe
#PBS -e /home/suffi.azizan/scratchspace/pipeline_scripts/tobias_snakemake_scripts/pbs_oe
#PBS -j oe


set -e
# Load modules
module purge
module load r/gcc6/4.2.0

# load conda environment
eval "$(conda shell.bash hook)"
conda activate snakemake_tobias

# check mode parameter

runmode=$MODE

# if mode equals to "dnase", run the following
if [[ "$runmode" == "dnase" ]]; then
    # run bias correction
    TOBIAS ATACorrect -b /home/msazizan/cargospace/encd-atac-pl/impo/tobias_benchmarking/128T8B4-AML_vs_T04OBGX-mono/128T8B4-AML/dedup_bams/128T8B4_sample2/align/rep1/C20FWACXX_lane3_4174_CAGATC_L003_R1.trim.srt.nodup.no_chrM_MT.bam -g /home/msazizan/hyperspace/annotations/GRCh38_no_alt_GCA_000001405.15.fasta -p /home/msazizan/cargospace/encd-atac-pl/impo/tobias_benchmarking/128T8B4-AML_vs_T04OBGX-mono/128T8B4-AML/merged_peaks/merged_sample2/merged_peaks_128T8B4-AML_sample2_3cols.bed --blacklist /home/msazizan/hyperspace/annotations/hg38-blacklist.v2.bed --read_shift 0 0 --k_flank 6 --outdir /home/msazizan/cargospace/encd-atac-pl/impo/tobias_benchmarking/dnase-test-run-10cores-odin --prefix "128T8B4-dnaseq-fp-sample2" --cores 10 &> /home/msazizan/hyperspace/footprinting-workflow-scripts/logs/tobias_basic_dnase-atacorrect-10cores-retest.log
    # score bigwigs
    TOBIAS ScoreBigwig --signal /home/msazizan/cargospace/encd-atac-pl/impo/tobias_benchmarking/dnase-test-run-10cores-odin/128T8B4-dnaseq-fp-sample2_corrected.bw --regions /home/msazizan/cargospace/encd-atac-pl/impo/tobias_benchmarking/128T8B4-AML_vs_T04OBGX-mono/128T8B4-AML/merged_peaks/merged_sample2/merged_peaks_128T8B4-AML_sample2_3cols.bed --output /home/msazizan/cargospace/encd-atac-pl/impo/tobias_benchmarking/dnase-test-run-10cores-odin/128T8B4-dnaseq-fp-sample2_footprints.bw --cores 10 &> /home/msazizan/hyperspace/footprinting-workflow-scripts/logs/tobias_basic_dnase-scorebw-10cores-retest.log
    # call footprints
    TOBIAS BINDetect --motifs /home/msazizan/hyperspace/footprinting-workflow-scripts/motif-guided/joined_filt_combined_motifs.jaspar --signals /home/msazizan/cargospace/encd-atac-pl/impo/tobias_benchmarking/dnase-test-run-10cores-odin/128T8B4-dnaseq-fp-sample2_footprints.bw --genome /home/msazizan/hyperspace/annotations/GRCh38_no_alt_GCA_000001405.15.fasta --peaks /home/msazizan/cargospace/encd-atac-pl/impo/tobias_benchmarking/128T8B4-AML_vs_T04OBGX-mono/128T8B4-AML/merged_peaks/merged_sample2/merged_peaks_128T8B4-AML_sample2_3cols.bed --outdir /home/msazizan/cargospace/encd-atac-pl/impo/tobias_benchmarking/dnase-test-run-10cores-odin/bindetect_outputs --skip-excel --cores 10 &> /home/msazizan/hyperspace/footprinting-workflow-scripts/logs/tobias_basic_dnase-bindetect-10cores-retest.log
elif [[ "$runmode" == "atac" ]]; then
    # run bias correction
    TOBIAS ATACorrect -b /home/msazizan/cargospace/encd-atac-pl/impo/tobias_benchmarking/128T8B4-AML_vs_T04OBGX-mono/128T8B4-AML/dedup_bams/128T8B4_sample1/align/rep1/C20BGACXX_lane6_3754_ACAGTG_L006_R1.trim.srt.nodup.no_chrM_MT.bam -g /home/msazizan/hyperspace/annotations/GRCh38_no_alt_GCA_000001405.15.fasta -p input.peaks --blacklist /home/msazizan/hyperspace/annotations/hg38-blacklist.v2.bed --outdir /home/msazizan/cargospace/encd-atac-pl/impo/tobias_benchmarking/output_dir_benchmarked --prefix "atacseq-fp-sample1" --cores 10 &> tobias_basic_atac-atacorrect_run-10c.log
    # score bigwigs
    TOBIAS ScoreBigwig --signal /home/msazizan/cargospace/encd-atac-pl/impo/tobias_benchmarking/output_dir_benchmarked/atacseq-fp-sample1_corrected.bw --regions input.peaks --output /home/msazizan/cargospace/encd-atac-pl/impo/tobias_benchmarking/output_dir_benchmarked/atacseq-fp-sample1_footprints.bw --cores 10 &> tobias_basic_atac-scorebw_run-10c.log
    # call footprints
    TOBIAS BINDetect --motifs /home/msazizan/hyperspace/footprinting-workflow-scripts/motif-guided/joined_filt_combined_motifs.jaspar --signals /home/msazizan/cargospace/encd-atac-pl/impo/tobias_benchmarking/output_dir_benchmarked/atacseq-fp-sample1_footprints.bw --genome /home/msazizan/hyperspace/annotations/GRCh38_no_alt_GCA_000001405.15.fasta --peaks input.peaks --outdir /home/msazizan/cargospace/encd-atac-pl/impo/tobias_benchmarking/output_dir_benchmarked/bindetect_outputs --skip-excel --cores 10 &> tobias_basic_atac-bindetect_run-10c.log
fi
