#!/usr/bin/env bash

# Check for correct number of arguments
if [ "$#" -ne 4 ]; then
    echo "Usage: $0 <gathered_input_root> <dataset_record> <run_number> <run_type>"
    exit 1
fi

gathered_input_root=$1
dataset_rec=$2
run_num=$3
# set run type
run_type=$4

# Set cores
cores=64

# Set peak file path based on run type
if [ "$run_type" == "union" ]; then
    true
elif [ "$run_type" == "master" ]; then
    peakfile="/scratch/users/ntu/suffiazi/inputs/peak_files/brca_subtype_merged/master_BRCA_merged_peaks/master_BRCA_merged_peaks-v1.bed"
else
    echo "Invalid run type. Please specify either <union> or <master>."
    exit 1
fi

echo "Gathered input root: $gathered_input_root"
echo "Dataset record: $dataset_rec"
echo "Run number: $run_num"

# Declare an associative array to store the dataset and experiment type pairs
declare -A dataset_dict

# Read the dataset record file and populate the associative array
while read -r dataset experiment; do
    dataset_dict["$dataset"]="$experiment"
done < "$dataset_rec"

echo array key "${!dataset_dict[@]}"
echo array val "${dataset_dict[@]}"

# Print the dataset and experiment type pairs
for dataset in "${!dataset_dict[@]}"; do
    # get the path of the dataset in the gathered_input_root
    dataset_bam=$(find "${gathered_input_root}" -maxdepth 1 -mindepth 1 -type f -name "${dataset}*.bam")
	# check if the dataset path is empty; if it is empty, skip
	if [ -z "${dataset_bam}" ]; then
        echo "Dataset ${dataset} merged bam file does not exist in input path. Skipping..."
		continue
	fi
    # assign the experiment type to a variable
    experiment_type="${dataset_dict[$dataset]}"
    echo "Dataset: $dataset Experiment Type: $experiment_type"
    
    # create the output directory
    echo mkdir -p "/home/users/ntu/suffiazi/scratch/outputs/tobias-outs/RUN-${run_num}-${run_type}-BRCA/${dataset}"
    
    # run the script
    qsub -v ANALYSIS_ID="${dataset}",EXP_TYPE="${experiment_type}",RUN="${run_num}",CORE="${cores}",PEAKS="${peakfile}",FILE="${dataset_bam}",TYPES="${run_type}" -N tobias-merged-run-"${dataset}" /home/users/ntu/suffiazi/scripts/footprinting-workflow-scripts/scripts/run_tobias_batch_aspire_main_BRCA-custom-submit.pbs
done