#!/usr/bin/env bash
# shellcheck disable=SC1091
set -e
eval "$(conda shell.bash hook)"
conda activate bashATAC

# check mode parameter

mode=$1

# if mode equals to "dnase", run the following
if [[ "$mode" == "dnase" ]]; then
    # run bias correction
    TOBIAS ATACorrect -b /home/msazizan/cargospace/encd-atac-pl/impo/tobias_benchmarking/128T8B4-AML_vs_T04OBGX-mono/128T8B4-AML/dedup_bams/128T8B4_sample1/align/rep1/C20BGACXX_lane6_3754_ACAGTG_L006_R1.trim.srt.nodup.no_chrM_MT.bam -g /home/msazizan/hyperspace/annotations/GRCh38_no_alt_GCA_000001405.15.fasta -p /home/msazizan/cargospace/encd-atac-pl/impo/tobias_benchmarking/128T8B4-AML_vs_T04OBGX-mono/128T8B4-AML/merged_peaks/merged_sample1/merged_peaks_128T8B4-AML_sample1_3cols.bed --blacklist /home/msazizan/hyperspace/annotations/hg38-blacklist.v2.bed --read_shift 0 0 --k_flank 6 --outdir /home/msazizan/cargospace/encd-atac-pl/impo/tobias_benchmarking/output_dir_benchmarked --prefix "128T8B4-dnaseq-fp-sample1" --cores 10 &> tobias_basic_dnase-atacorrect_run-10c.log
    # score bigwigs
    TOBIAS ScoreBigwig --signal /home/msazizan/cargospace/encd-atac-pl/impo/tobias_benchmarking/output_dir_benchmarked/128T8B4-dnaseq-fp-sample1_corrected.bw --regions /home/msazizan/cargospace/encd-atac-pl/impo/tobias_benchmarking/128T8B4-AML_vs_T04OBGX-mono/128T8B4-AML/merged_peaks/merged_sample1/merged_peaks_128T8B4-AML_sample1_3cols.bed --output /home/msazizan/cargospace/encd-atac-pl/impo/tobias_benchmarking/output_dir_benchmarked/128T8B4-dnaseq-fp-sample1_footprints.bw --cores 10 &> tobias_basic_dnase-scorebw_run-10c.log
    # call footprints
    TOBIAS BINDetect --motifs /home/msazizan/hyperspace/footprinting-workflow-scripts/motif-guided/joined_filt_combined_motifs.jaspar --signals /home/msazizan/cargospace/encd-atac-pl/impo/tobias_benchmarking/output_dir_benchmarked/128T8B4-dnaseq-fp-sample1_footprints.bw --genome /home/msazizan/hyperspace/annotations/GRCh38_no_alt_GCA_000001405.15.fasta --peaks /home/msazizan/cargospace/encd-atac-pl/impo/tobias_benchmarking/128T8B4-AML_vs_T04OBGX-mono/128T8B4-AML/merged_peaks/merged_sample1/merged_peaks_128T8B4-AML_sample1_3cols.bed --outdir /home/msazizan/cargospace/encd-atac-pl/impo/tobias_benchmarking/output_dir_benchmarked/bindetect_outputs --skip-excel --cores 10 &> tobias_basic_dnase-bindetect_run-10c.log
elif [[ "$mode" == "atac" ]]; then
    # run bias correction
    TOBIAS ATACorrect -b /home/msazizan/cargospace/encd-atac-pl/impo/tobias_benchmarking/128T8B4-AML_vs_T04OBGX-mono/128T8B4-AML/dedup_bams/128T8B4_sample1/align/rep1/C20BGACXX_lane6_3754_ACAGTG_L006_R1.trim.srt.nodup.no_chrM_MT.bam -g /home/msazizan/hyperspace/annotations/GRCh38_no_alt_GCA_000001405.15.fasta -p input.peaks --blacklist /home/msazizan/hyperspace/annotations/hg38-blacklist.v2.bed --outdir /home/msazizan/cargospace/encd-atac-pl/impo/tobias_benchmarking/output_dir_benchmarked --prefix "atacseq-fp-sample1" --cores 10 &> tobias_basic_atac-atacorrect_run-10c.log
    # score bigwigs
    TOBIAS ScoreBigwig --signal /home/msazizan/cargospace/encd-atac-pl/impo/tobias_benchmarking/output_dir_benchmarked/atacseq-fp-sample1_corrected.bw --regions input.peaks --output /home/msazizan/cargospace/encd-atac-pl/impo/tobias_benchmarking/output_dir_benchmarked/atacseq-fp-sample1_footprints.bw --cores 10 &> tobias_basic_atac-scorebw_run-10c.log
    # call footprints
    TOBIAS BINDetect --motifs /home/msazizan/hyperspace/footprinting-workflow-scripts/motif-guided/joined_filt_combined_motifs.jaspar --signals /home/msazizan/cargospace/encd-atac-pl/impo/tobias_benchmarking/output_dir_benchmarked/atacseq-fp-sample1_footprints.bw --genome /home/msazizan/hyperspace/annotations/GRCh38_no_alt_GCA_000001405.15.fasta --peaks input.peaks --outdir /home/msazizan/cargospace/encd-atac-pl/impo/tobias_benchmarking/output_dir_benchmarked/bindetect_outputs --skip-excel --cores 10 &> tobias_basic_atac-bindetect_run-10c.log
fi
