#!/usr/bin/env bash
# shellcheck disable=SC1091
# shellcheck disable=SC2153
# This script is used to run the job on the NSCC cluster.

#PBS -N tobias-union-run-1
#PBS -l select=1:ncpus=64:mem=128GB
#PBS -l walltime=8:00:00
#PBS -j oe
#PBS -P personal
#PBS -q normal

# load conda environment
module load miniconda3/py38_4.8.3
conda activate /home/users/ntu/suffiazi/apps/mambaforge/envs/tobias-footprinting

dataset=$ANALYSIS_ID
sample_name=$SAMPLE
experiment_type=$EXP_TYPE
run_num=$RUN
cores=$CORE
masterpeaks=$MASTER_PEAK
bam=$FILE

# check if the experiment type is DNase-seq
if [[ "$experiment_type" == "dnaseseq" ]]; then
    # run bias correction
    echo "Running bias correction for ${dataset}_${sample_name}"
    if TOBIAS ATACorrect -b "$bam" -g /home/users/ntu/suffiazi/genomes/GRCh38_no_alt_GCA_000001405.15.fasta -p "${masterpeaks}" --blacklist /home/users/ntu/suffiazi/genomes/hg38-blacklist.v2.bed --read_shift 0 0 --k_flank 6 --outdir "/home/users/ntu/suffiazi/scratch/outputs/tobias-outs/RUN-${run_num}-master/${dataset}_${sample_name}" --prefix "${dataset}_${sample_name}" --cores "${cores}" >> "/home/users/ntu/suffiazi/scripts/footprinting-workflow-scripts/logfiles/${dataset}_${sample_name}_${experiment_type}-${cores}cores-aspire-${run_num}-master.log"; then
        echo "Bias correction has been completed for ${dataset}_${sample_name}. Proceeding with footprinting."
    else
        echo "ERROR: Bias correction has failed for ${dataset}_${sample_name}. Please check the log file for more details."
        exit 1
    fi
elif [[ "$experiment_type" == "atacseq" ]]; then
    # run bias correction
    echo "Running bias correction for ${dataset}_${sample_name}"
    if TOBIAS ATACorrect -b "$bam" -g /home/users/ntu/suffiazi/genomes/GRCh38_no_alt_GCA_000001405.15.fasta -p "${masterpeaks}" --blacklist /home/users/ntu/suffiazi/genomes/hg38-blacklist.v2.bed --outdir "/home/users/ntu/suffiazi/scratch/outputs/tobias-outs/RUN-${run_num}-master/${dataset}_${sample_name}" --prefix "${dataset}_${sample_name}" --cores "${cores}" >> "/home/users/ntu/suffiazi/scripts/footprinting-workflow-scripts/logfiles/${dataset}_${sample_name}_${experiment_type}-${cores}cores-aspire-${run_num}-master.log"; then
        echo "Bias correction has been completed for ${dataset}_${sample_name}. Proceeding with footprinting."
    else
        echo "ERROR: Bias correction has failed for ${dataset}_${sample_name}. Please check the log file for more details."
        exit 1
    fi
fi

FILELIMIT=$(ulimit -n)
echo "Current file descriptor limit: " "$FILELIMIT"

# run TOBIAS footprinting
# score bigwigs
echo "Scoring bigwigs for ${dataset}_${sample_name} and calling footprints..."
if TOBIAS ScoreBigwig --signal "/home/users/ntu/suffiazi/scratch/outputs/tobias-outs/RUN-${run_num}-master/${dataset}_${sample_name}/${dataset}_${sample_name}_corrected.bw" --regions "${masterpeaks}" --output "/home/users/ntu/suffiazi/scratch/outputs/tobias-outs/RUN-${run_num}-master/${dataset}_${sample_name}/${dataset}_${sample_name}_footprints.bw" --cores "${cores}" >> "/home/users/ntu/suffiazi/scripts/footprinting-workflow-scripts/logfiles/${dataset}_${sample_name}_${experiment_type}-${cores}cores-aspire-${run_num}-master.log" && \
# call footprints
TOBIAS BINDetect --motifs /home/users/ntu/suffiazi/scripts/footprinting-workflow-scripts/motif-guided/joined_filt_combined_motifs.jaspar --signals "/home/users/ntu/suffiazi/scratch/outputs/tobias-outs/RUN-${run_num}-master/${dataset}_${sample_name}/${dataset}_${sample_name}_footprints.bw" --genome /home/users/ntu/suffiazi/genomes/GRCh38_no_alt_GCA_000001405.15.fasta --peaks "${masterpeaks}" --outdir "/home/users/ntu/suffiazi/scratch/outputs/tobias-outs/RUN-${run_num}-master/${dataset}_${sample_name}/bindetect_outputs" --skip-excel --cores "${cores}" >> "/home/users/ntu/suffiazi/scripts/footprinting-workflow-scripts/logfiles/${dataset}_${sample_name}_${experiment_type}-${cores}cores-aspire-${run_num}.log"; then
    echo "Successfully ran TOBIAS footprinting for ${dataset}_${sample_name}."
else
    echo "ERROR: Failed to run TOBIAS footprinting for ${dataset}_${sample_name} due to an error. Please see the log file for more details."
    exit 1
fi

echo "All done! Check the log files for any errors and the outputs directory for the results."
