#!/usr/bin/env bash
# shellcheck disable=SC1091
# shellcheck disable=SC2153
# This script is used to run the job on the Gekko cluster.

#PBS -N hint-atac
#PBS -P sbs_liyh

#PBS -q q128
#PBS -l select=1:ncpus=16:mpiprocs=16:mem=8gb
#PBS -l walltime=6:00:00

#PBS -m bea
#PBS -M suffi.azizan@ntu.edu.sg
#PBS -j oe

# load module files
module load singularity

# load conda environment
eval "$(conda shell.bash hook)"
conda activate rgt-suite

out_prefix=$OUT_PREF
bam=$FILE
peaks=$MERGED_PEAKS
path_output=$OUT_PATH

# run rgt-hint
#rgt-hint footprinting --atac-seq --paired-end --organism hg38 --output-prefix "${out_prefix}" --output-location "${path_output}" "${bam}" "${peaks}"

# run bedtools getfasta
cut -f 1,2,3 "${path_output}"/"${out_prefix}".bed | bedtools getfasta -fi /home/suffi.azizan/scratchspace/inputs/genomes/GRCh38_no_alt_GCA_000001405.15.fasta -bed - -fo /home/suffi.azizan/scratchspace/outputs/streme-io/inputs/"${out_prefix}"_footprints.fa

# run streme
singularity exec --bind /scratch/suffi.azizan:/mnt /home/suffi.azizan/installs/singularity_sifs/memesuite.sif streme --verbosity 1 --oc /mnt/outputs/streme-io/outputs/"${out_prefix}" --dna --totallength 4000000 --minw 8 --maxw 15 --thresh 0.05 --align center --p /mnt/outputs/streme-io/inputs/"${out_prefix}"_footprints.fa
