#!/usr/bin/env bash

######### FOR RUNNING ON GEKKO CLUSTER #########
# load environment
eval "$(conda shell.bash hook)"
conda activate rgt-suite

set -eo noclobber
set -eo pipefail

# run rgt-hint
rgt-hint footprinting --atac-seq --paired-end --organism hg38 --output-prefix "fp" --output-location /home/suffi.azizan/scratchspace/outputs/hint-atac "$BAM" "$MERGED_BED"