#!/usr/bin/env bash
# shellcheck disable=SC1091
# shellcheck disable=SC2153
# This script is used to run the job on the Gekko cluster.

#PBS -N hint-atac
#PBS -P sbs_liyh

#PBS -q q128
#PBS -l select=1:ncpus=16:mpiprocs=16:mem=32gb
#PBS -l walltime=5:00:00

#PBS -m bea
#PBS -M suffi.azizan@ntu.edu.sg
#PBS -j oe

# load module files
module load singularity

# load conda environment
eval "$(conda shell.bash hook)"
conda activate rgt-suite

out_prefix=$OUT_PREF
bam=$FILE
peaks=$MERGED_PEAKS

# run rgt-hint
rgt-hint footprinting --atac-seq --paired-end --organism hg38 --output-prefix "${out_prefix}" --output-location /home/suffi.azizan/scratchspace/outputs/hint-atac/hint-atac-outputs "${bam}" "${peaks}" >> "/home/suffi.azizan/scratchspace/outputs/hint-atac/logs/hint-run-${out_prefix}.log" 2>&1

# run bedtools getfasta
#bedtools getfasta -fi /home/suffi.azizan/scratchspace/inputs/genomes/GRCh38_no_alt_GCA_000001405.15.fasta -bed /home/suffi.azizan/scratchspace/outputs/hint-atac/1KEQR84-nBCt/fp_paired_nbctons-"$i"for-streme.bed -fo /home/suffi.azizan/scratchspace/outputs/streme-io/1KEQR84-nBCt-"$i"-footprints.fa

# run streme
#singularity shell --bind /scratch/suffi.azizan:/mnt memesuite.sif
# /opt/meme/bin/streme
#streme --verbosity 1 --oc . --dna --totallength 4000000 --time 14399 --minw 8 --maxw 15 --thresh 0.05 --align center --p /mnt/outputs/streme-io/JD32HPP-MCL/mcl-1/fp_paired_mcl-1.bed-for-streme.bed.fa
